#!/usr/bin/perl

use Term::ANSIColor qw(:constants);
no warnings;
use File::Copy qw(move);
use File::Copy qw(copy);
print("\n");
  print(YELLOW"================================================================================================\n");
  print(WHITE"                                  DFT Method Based on PMTP Approach.....\n");
  print(WHITE"                                  Version 2.0, Released:: July 2018\n");
  print(WHITE"                                  Designed By:: Ahmad Shabani\n");
  print(WHITE"                                  Tehran University, Tehran, Iran\n");
  print(WHITE"                                  Contact::ah.shabani(at)ut.ac.ir\n");
  print(WHITE"                                          ahmadshabani89(at)gmail.com\n");
  print(WHITE"                                 For more info please visit:: dvdes.ut.ac.ir\n");

  print(YELLOW"=================================================================================================\n");

open(data1,"<config.txt");
while($line=<data1>){
	if($line=~m /Design_Name/x){
     ($Design)=$line=~m /Design_Name=\s*(\w+)/x;
	 $Design=$Design.'.v';
	}
	elsif($line=~m /Test_Bench/x){
     ($TB_Design)=$line=~m /Test_Bench=\s*(\w+)/x;
	 $TB_Design=$TB_Design.'.v';
	}
	elsif($line=~m /Probability_Threshold/x){
     ($Pth)=$line=~m /Probability_Threshold=\s*(\d+.\d+)/x;
	}
	elsif($line=~m /NumOfTest/x){
     ($NumTest)=$line=~m /NumOfTest=\s*(\d+)/x;
	}
	elsif($line=~m /CycleTime/x){f
     ($CycleTime)=$line=~m /CycleTime=\s*(\d+)/x;
	}
	else{

	}
}
  close data1;
  print("Circuit Netlist::$Design\n");
  print("Test_Bench::$TB_Design\n");

  open(data2,">script.do");
  print(data2 "vlib work\n");
  print(data2 "vlog $TB_Design $Design\n");
  print(data2 "vsim work.tb_Design\n");
  print(data2 "run -all\n");
  close data2;
#******************************************************************************
#								Running Modelsim for run1.do script ...
#******************************************************************************
print("\n");
  print(YELLOW"================================================================================================\n");
  print(YELLOW"                                Running Modelsim.....\n");
  print(YELLOW"=================================================================================================\n");
$cmd='vsim -c -do script.do';
system($cmd);
print(YELLOW,"...Modelsim Done............\n");
print(WHITE,"\n");
print("\n");
  print(YELLOW"================================================================================================\n");
  print(YELLOW"                                  Coverting VCD to Saif File.....\n");
  print(YELLOW"=================================================================================================\n");
$cmd='vcd2saif -input Design.vcd -output Design_bw.saif';
system($cmd);
##=============================================================================================================
$NumTest=$NumTest;					#number of testvectors
$CycleTime=$CycleTime;					# every 5ns we insert a new test vector
$DURATION=$NumTest*$CycleTime;  # total time of simulation
$Pth=$Pth;						# threshold of probablity

print("\nConfiguration...\n--------------------\n \t#Test Vectors::$NumTest\n \tCycleTime::$CycleTime ns\n \tDuration::$DURATION ns\n \tPTh::$Pth\n");
#=============================================================================================
#extracting information of TC (number of Transition) and TR (transition Rate) from saif file generated by modelsim
open(data_in,"< Design_bw.saif");
open(data_out,">Probablity.out");
# Ex:     (N223
#				(T0 390000) (T1 4605000) (TX 0)
#				(TC 140) (IG 0)
#
no warnings;
while($line=<data_in>){
	chomp($line);
	if($line=~m /INSTANCE \s U0 /x){
		<data_in>;# go to next line
		last;
	}
}
while($line=<data_in>){
	chomp($line);
	if($line=~m /\((\w+)$/x){
	 	 (my $node)=$line=~m /\((\w+)$/x; # extract node
	     $line=<data_in>;  # extarct information of node from saif file
	     (my $T0,my $T1, my $TX)=$line=~m /\(\w+\s(\d+)\) \s+ \(\w+\s(\d+)\) \s+ \(\w+\s(\d+)\)/x;
	     $line=<data_in>;
	     (my $TC)=$line=~m/\(\w+\s(\d+)\)/x;
		 $T0_h{$node}=$T0; # adding to the hashes
		 $T1_h{$node}=$T1;
		 $P0_h{$node}=$T0/($DURATION*1000);
		 $P1_h{$node}=$T1/($DURATION*1000);
		 $prob_h{$node}=$P0_h{$node}*$P1_h{$node};
		 $TR_h{$node}=$TC/$DURATION;
		 $TC_h{$node}=$TC;
		 #$prob_h{$node}=$TC_h{$node}/(2*$NumTest);
		 push(@MyNodes,$node) unless grep{$_ eq $node} @MyNodes; # all the nodes
		}
}
print(data_out "node\t\t P1\t\t\t\t P0\t\t\t\t\ Pt\t\t\t\tToggleRate\t#Transition\n=====================================================================================================\n");
foreach $var (@MyNodes){
	printf (data_out "%-10s  %-f \t %-f \t\t\t%-f\t\t%-f\t\t%-5.1f\n", $var, $P1_h{$var}, $P0_h{$var}, $prob_h{$var},$TR_h{$var},$TC_h{$var});
	if($prob_h{$var}==0){
		    if($P1_h{$var}==1){
			$stucked_h{$var}=1;
			}
		else{
			$stucked_h{$var}=0;
			}
	  }
}
print(data_out "===============================================================================================================\n");
close data_in;
close data_out;
print(YELLOW,"...VCD to SAIF Done............\n");
