#!/usr/bin/perl
require "Pre-processingSAT_mode1.pl";
no warnings;
use Term::ANSIColor qw(:constants);
open(myfile,"> Design.cnf");
print("\n");
  print(YELLOW"================================================================================================\n");
  print(YELLOW"                                 CNF File Generation.....\n");
  print(YELLOW"=================================================================================================\n");use Switch;
print (myfile "c CNF generated By Ahmad Shabani\n");
print ("CNF generated By Ahmad Shabani (Design.cnf)\n");

print(myfile "p cnf $NumVar 29\n");
$cnt=0;
foreach $node (@INTNodes){ 
    my $TypeNode=$info_h{$node}{"type"};
	my $out=$info_h{$node}{"map"};
	my $in1=$info_h{$info_h{$node}{"fanin1"}}{"map"};
	my $in2=$info_h{$info_h{$node}{"fanin2"}}{"map"};
	
  switch($TypeNode){
   case AND2           {	#print("Type::$TypeNode\n");
							#print($info_h{$node}{"fanin1"},"\t",$info_h{$node}{"fanin2"},"\t",$node,"\n");
							#print("$in1\t$in2\t$out\n======================\n\n");
							print(myfile "-$in1 -$in2 $out 0\n");
							print(myfile "$in1 -$out 0\n");					
							print(myfile "$in2 -$out 0\n");
							$cnt=$cnt+3;
												}
   case NAND2          {	#print("Type::$TypeNode\n");
							#print($info_h{$node}{"fanin1"},"\t",$info_h{$node}{"fanin2"},"\t",$node,"\n");
							#print("$in1\t$in2\t$out\n======================\n\n");
						if(grep( /^$node$/, @X_sort)){# like and gate
							print(myfile "-$in1 -$in2 $out 0\n");
							print(myfile "$in1 -$out 0\n");					
							print(myfile "$in2 -$out 0\n");
							$cnt=$cnt+3;
							}
						else{# like nand gate
							print(myfile "-$in1 -$in2 -$out 0\n");
							print(myfile "$in1 $out 0\n");					
							print(myfile "$in2 $out 0\n");
							$cnt=$cnt+3;
							}
													
												}
   
   case OR2            {	#print("Type::$TypeNode\n");
							#print($info_h{$node}{"fanin1"},"\t",$info_h{$node}{"fanin2"},"\t",$node,"\n");
							#print("$in1\t$in2\t$out\n======================\n\n");
							print(myfile "$in1 $in2 -$out 0\n");
							print(myfile "-$in1 $out 0\n");					
							print(myfile "-$in2 $out 0\n");	
							$cnt=$cnt+3;
												}
												
   case NOR2           {	#print("Type::$TypeNode\n");
							#print($info_h{$node}{"fanin1"},"\t",$info_h{$node}{"fanin2"},"\t",$node,"\n");
							#print("$in1\t$in2\t$out\n======================\n\n");
						if( grep( /^$node$/, @X_sort)){# like or gate
							print(myfile "$in1 $in2 -$out 0\n");
							print(myfile "-$in1 $out 0\n");					
							print(myfile "-$in2 $out 0\n");
							$cnt=$cnt+3;
							}
						else{# like nor gate
							print(myfile "$in1 $in2 $out 0\n");
							print(myfile "-$in1 -$out 0\n");					
							print(myfile "-$in2 -$out 0\n");
							$cnt=$cnt+3;
							}
													
												}
												
												
   case XOR2           {	#print("Type::$TypeNode\n");
							#print($info_h{$node}{"fanin1"},"\t",$info_h{$node}{"fanin2"},"\t",$node,"\n");
							#print("$in1\t$in2\t$out\n======================\n\n");
							print(myfile "-$in1 -$in2 -$out 0\n");
							print(myfile "$in1 $in2 -$out 0\n");
							print(myfile "$in1 -$in2 $out 0\n");
							print(myfile "-$in1 $in2 $out 0\n");
							$cnt=$cnt+4;
												}
												
   case XNOR2          {	#print("Type::$TypeNode\n");
							#print($info_h{$node}{"fanin1"},"\t",$info_h{$node}{"fanin2"},"\t",$node,"\n");
							#print("$in1\t$in2\t$out\n======================\n\n");
						if( grep( /^$node$/, @X_sort)){# like xor gate
							print(myfile "-$in1 -$in2 -$out 0\n");
							print(myfile "$in1 $in2 -$out 0\n");
							print(myfile "$in1 -$in2 $out 0\n");
							print(myfile "-$in1 $in2 $out 0\n");
							$cnt=$cnt+4;
							}
						else{# like xnor gate
							print(myfile "-$in1 -$in2 $out 0\n");
							print(myfile "$in1 $in2 $out 0\n");
							print(myfile "$in1 -$in2 -$out 0\n");
							print(myfile "-$in1 $in2 -$out 0\n");
							$cnt=$cnt+4;
							}
													
												}
   
   case NOT1           {	#print("Type::$TypeNode\n");
							#print($info_h{$node}{"fanin1"},"\t",$node,"\n");
							#print("$in1\t$out\n======================\n\n");
							print(myfile "-$in1 -$out 0\n");
							print(myfile "$in1 $out 0\n");
							$cnt=$cnt+2;
												}
												
												
   case BUFF1          {	#print("Type::$TypeNode\n");
							#print($info_h{$node}{"fanin1"},"\t",$node,"\n");
							#print("$in1\t$out\n======================\n\n");
							print(myfile "-$in1 $out 0\n");
							print(myfile "$in1 -$out 0\n");	
							$cnt=$cnt+2;
												}
   else              { print (RED,"node type is not supported") }
   }
}

print("Number of Cluases::$cnt\n");
print("Number of Variables::$NumVar\n");
close myfile;

#open(myfile,"+>> Design.cnf");
#    while($line=<myfile>){
#		if($line=~m /p \s cnf/x){
#	        print (myfile "p cnf $NumVar $cnt");
#			}
#		else{
#		   # print (myfile "$line");
#
#			}
#		}

close myfile;

print(YELLOW,"....CNF Generation Done................................\n");